FROM python:3.9-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY ./backend/ .

# Make migrations directory
RUN mkdir -p quizzes/migrations

# Expose port
EXPOSE 8080

# Start command
#CMD ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"]
CMD ["sh", "-c", "echo '🔄 Running makemigrations...' && python manage.py makemigrations  && echo '✅ Migrations complete!' && echo '🔄 For force migrating database... docker exec -it quizwizz-backend python manage.py migrate --run-syncdb' && python manage.py runserver 0.0.0.0:8080 "]