# Generated by Django 5.2.6 on 2025-11-03 10:59

from django.db import migrations


def seed_quizzes(apps, schema_editor):
    Tag = apps.get_model("quizzes", "Tag")
    Quiz = apps.get_model("quizzes", "Quiz")
    Question = apps.get_model("quizzes", "Question")
    Choice = apps.get_model("quizzes", "Choice")

    legacy_ids = {
        "q-geometry",
        "q-history-intro",
        "q-history-middle-ages",
        "q-history-modern-times",
        "q-history-contemporary-times",
        "q-history-20th-century",
        "q-history-21st-century",
    }
    Quiz.objects.filter(id__in=legacy_ids).delete()

    dataset = [
    {
        "id": "q-math-hard",
        "name": "Math test",
        "author": "Klara",
        "tags": ["math", "numbers"],
        "questions": [
          {
            "id": "a",
            "text": "What equals 11 x 11?",
            "options": ["121", "111", "131", "120"],
            "correctIndex": 0,
        },
        {
            "id": "b",
            "text": "What is 18 divided by 3?",
            "options": ["9", "3", "6", "8"],
            "correctIndex": 2,
        },
        {
            "id": "c",
            "text": "What equals 99 - 35?",
            "options": ["65", "64", "66", "68"],
            "correctIndex": 1,
        },
          {
          "id": "d",
          "text": "What is pi?",
          "options": ["3", "4.15", "3.14", "-3"],
          "correctIndex": 2,
      },
      {
            "id": "e",
            "text": "What is 89 x 4?",
            "options": ["326", "346", "296", "356"],
            "correctIndex": 3,
        }
        ]     
         },
        {
            "id": "q-math-basics",
            "name": "Math Sprint",
            "author": "Alice",
            "tags": ["math", "numbers"],
            "questions": [
                {
                    "id": "add-2",
                    "text": "2 + 3 = ?",
                    "options": ["4", "5", "6", "7"],
                    "correctIndex": 1,
                },
                {
                    "id": "double",
                    "text": "What is double of 8?",
                    "options": ["14", "16", "18", "10"],
                    "correctIndex": 1,
                },
                {
                    "id": "fraction",
                    "text": "Which is greater?",
                    "options": ["1/3", "1/2", "1/4", "1/5"],
                    "correctIndex": 1,
                },
            ],
        },
        {
            "id": "q-planet-facts",
            "name": "Planet Quick Facts",
            "author": "Ravi",
            "tags": ["science", "space"],
            "questions": [
                {
                    "id": "hottest",
                    "text": "Hottest planet in our solar system?",
                    "options": ["Mercury", "Venus", "Earth", "Mars"],
                    "correctIndex": 1,
                },
                {
                    "id": "rings",
                    "text": "Which planet has the most visible rings?",
                    "options": ["Saturn", "Neptune", "Jupiter", "Uranus"],
                    "correctIndex": 0,
                },
                {
                    "id": "day",
                    "text": "Planet with the longest day?",
                    "options": ["Venus", "Earth", "Mars", "Mercury"],
                    "correctIndex": 0,
                },
            ],
        },
        {
            "id": "q-coding-first-steps",
            "name": "Coding First Steps",
            "author": "Lina",
            "tags": ["technology", "programming"],
            "questions": [
                {
                    "id": "binary",
                    "text": "Binary uses which digits?",
                    "options": ["0 and 1", "1 and 2", "2 and 4", "1 and 4"],
                    "correctIndex": 0,
                },
                {
                    "id": "html",
                    "text": "HTML is used to describe?",
                    "options": ["Data logic", "Web pages", "Device drivers", "Games"],
                    "correctIndex": 1,
                },
                {
                    "id": "loop",
                    "text": "A loop repeats instructions until?",
                    "options": ["Program ends", "Condition met", "Memory full", "Computer sleeps"],
                    "correctIndex": 1,
                },
            ],
        },
        {
            "id": "q-artist-spotlight",
            "name": "Artist Spotlight",
            "author": "Maya",
            "tags": ["art", "history"],
            "questions": [
                {
                    "id": "mona-lisa",
                    "text": "Who painted the Mona Lisa?",
                    "options": ["Van Gogh", "Da Vinci", "Picasso", "Monet"],
                    "correctIndex": 1,
                },
                {
                    "id": "scream",
                    "text": "The Scream was created by?",
                    "options": ["Munch", "Klimt", "Dali", "Renoir"],
                    "correctIndex": 0,
                },
                {
                    "id": "starry-night",
                    "text": "Starry Night shows which village?",
                    "options": ["Giverny", "Arles", "Saint-Rémy", "Paris"],
                    "correctIndex": 2,
                },
            ],
        },
        {
            "id": "q-coffee-break-trivia",
            "name": "Coffee Break Trivia",
            "author": "Noah",
            "tags": ["general", "fun"],
            "questions": [
                {
                    "id": "largest-ocean",
                    "text": "Largest ocean on Earth?",
                    "options": ["Indian", "Pacific", "Atlantic", "Arctic"],
                    "correctIndex": 1,
                },
                {
                    "id": "novel",
                    "text": "Author of '1984'?",
                    "options": ["Orwell", "Huxley", "Bradbury", "Atwood"],
                    "correctIndex": 0,
                },
                {
                    "id": "currency-japan",
                    "text": "Currency used in Japan?",
                    "options": ["Yuan", "Won", "Yen", "Dollar"],
                    "correctIndex": 2,
                },
            ],
        },
    ]

    for record in dataset:
        quiz_id = record["id"]
        tags = record.get("tags", [])
        questions = record.get("questions", [])
        quiz_defaults = {
            "name": record["name"],
            "author": record["author"],
            "description": record.get("description", ""),
        }
        quiz, _ = Quiz.objects.update_or_create(id=quiz_id, defaults=quiz_defaults)
        tag_objects = [Tag.objects.get_or_create(name=tag)[0] for tag in tags]
        quiz.tags.set(tag_objects)

        seen_question_ids = []
        for order, question in enumerate(questions):
            base_qid = question["id"]
            question_id = f"{quiz_id}-{base_qid}"
            seen_question_ids.append(question_id)
            q_obj, _ = Question.objects.update_or_create(
                id=question_id,
                defaults={
                    "quiz": quiz,
                    "text": question["text"],
                    "order": order,
                },
            )
            Choice.objects.filter(question=q_obj).delete()
            for idx, option in enumerate(question.get("options", [])):
                Choice.objects.create(
                    question=q_obj,
                    index=idx,
                    text=option,
                    is_correct=idx == question.get("correctIndex", -1),
                )

        Question.objects.filter(quiz=quiz).exclude(id__in=seen_question_ids).delete()


def unseed_quizzes(apps, schema_editor):
    Quiz = apps.get_model("quizzes", "Quiz")

    legacy_ids = {
        "q-geometry",
        "q-history-intro",
        "q-history-middle-ages",
        "q-history-modern-times",
        "q-history-contemporary-times",
        "q-history-20th-century",
        "q-history-21st-century",
    }

    quiz_ids = [
        "q-math-basics",
        "q-planet-facts",
        "q-coding-first-steps",
        "q-artist-spotlight",
        "q-coffee-break-trivia",
        *legacy_ids,
    ]

    Quiz.objects.filter(id__in=quiz_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [migrations.RunPython(seed_quizzes, unseed_quizzes)]
