# Generated by Django on 2026-01-13
from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_default_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    
    # Create default users with simple passwords
    users_data = [
        {'username': 'alice', 'password': 'alice123', 'email': 'alice@example.com'},
        {'username': 'bob', 'password': 'bob123', 'email': 'bob@example.com'},
        {'username': 'charlie', 'password': 'charlie123', 'email': 'charlie@example.com'},
    ]
    
    for user_data in users_data:
        if not User.objects.filter(username=user_data['username']).exists():
            User.objects.create(
                username=user_data['username'],
                email=user_data['email'],
                password=make_password(user_data['password']),
                is_staff=False,
                is_superuser=False,
            )


def remove_default_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username__in=['alice', 'bob', 'charlie']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_users, remove_default_users),
    ]
