# Generated by Django 5.2.6 on 2025-12-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="icon",
            field=models.CharField(blank=True, default="📝", max_length=50),
        ),
    ]
