# Generated by Django 5.2.8 on 2025-12-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_seed_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
