# Generated by Django 3.2.25 on 2025-12-03 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_seed_coffee_quizzes'),
        ('quizzes', '0008_quiz_likes_dislikes'),
    ]

    operations = [
    ]
