# Generated by Django 5.2.8 on 2025-12-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_merge_20251203_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
