# Generated by Django 5.2.6 on 2025-12-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0010_choice_image_url_question_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True),
        ),
    ]
