# Generated by Django 5.2.6 on 2025-12-19 18:45

from django.db import migrations
from django.contrib.auth.hashers import make_password


def migrate_authors_to_users(apps, schema_editor):
    """Convert author CharField to User ForeignKey"""
    Quiz = apps.get_model('quizzes', 'Quiz')
    User = apps.get_model('auth', 'User')
    
    # Get all unique author names
    author_names = Quiz.objects.values_list('author', flat=True).distinct()
    
    # Create users for each author
    for author_name in author_names:
        if author_name:  # Skip empty authors
            # Check if user already exists
            user, created = User.objects.get_or_create(
                username=author_name,
                defaults={
                    'password': make_password(author_name),  # password same as username
                    'email': f'{author_name}@quizwizz.local',
                }
            )
            
            # Update all quizzes with this author
            Quiz.objects.filter(author=author_name).update(author_user=user)


def reverse_migration(apps, schema_editor):
    """Reverse the migration - copy User back to author CharField"""
    Quiz = apps.get_model('quizzes', 'Quiz')
    
    for quiz in Quiz.objects.all():
        if quiz.author_user:
            quiz.author = quiz.author_user.username
            quiz.save()


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0014_quiz_author_user"),
    ]

    operations = [
        migrations.RunPython(migrate_authors_to_users, reverse_migration),
    ]
