# Generated by Django 5.2.6 on 2025-12-19 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0016_remove_quiz_author_alter_quiz_author_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='author_user',
            new_name='author',
        ),
    ]
