# Generated by Django 3.2.25 on 2026-01-11 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0020_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'quiz')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['quiz', '-created_at'], name='quizzes_com_quiz_id_de4704_idx'),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
    ]
