# Generated by Django 3.2.25 on 2026-01-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0020_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'quiz')},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
    ]
