# Generated by Django 5.2.6 on 2026-01-12 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0020_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["quiz", "-created_at"], name="quizzes_com_quiz_id_de4704_idx"
            ),
        ),
    ]
