# Generated by Django 3.2.25 on 2026-01-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0022_pali_johi_testing_setup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
    ]
