# Generated by Django merge

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0021_auto_20260111_1646'),
        ('quizzes', '0022_pali_johi_testing_setup'),
    ]

    operations = [
    ]
