# Generated by Django to remove unique constraint on Comment

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0023_merge_20260112_0000'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
