# Generated by Django 3.2.25 on 2026-01-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0023_auto_20260112_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['quiz', '-created_at'], name='quizzes_com_quiz_id_de4704_idx'),
        ),
    ]
