# Generated by Django 5.2.6 on 2026-01-12 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0023_merge_20260112_1320"),
        ("quizzes", "0025_alter_favorite_unique_together"),
    ]

    operations = []
